export * from "./Logo/Logo";
export * from "./Header/Header";
export * from "./Wrapper/Wrapper";
export * from "./Main/Main";
export * from "./Title/Title";
export * from "./Services/Services";
export * from "./Team/Team";
export * from "./Form/Form";
export * from "./Footer/Footer";
